### ISSUE TITLE
Deployment error when I followed the "Steps to create a Chatbot in EDDI"

### ISSUE THREAD

**Issue by happyshows** [labsai/EDDI#122]
Hi,

I'm using the docker image with the docker-compose up command only.

Then I followed the [guide](https://labsai.atlassian.net/wiki/spaces/EDDI/pages/168410/Creating+your+first+Chatbot)

I have tried a couple times from the beginning but each time I got hit by a deployment error.

```
 2018-11-27 17:46:13,431 INFO  [etp284149112-39] ? (:) - Deploying Bot... (environment=unrestricted, botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | 2018-11-27 17:46:13,648 INFO  [etp284149112-39] ? (:) - Bot deployed with status: ERROR (environment=unrestricted, botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | 2018-11-27 17:46:13,649 ERROR [etp284149112-39] ? (:) - Error while deploying bot! (botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | ai.labs.runtime.service.ServiceException: HTTP 404 Not Found
eddi_1     | 	at ai.labs.runtime.service.PackageStoreService.getPackageDocumentDescriptor(PackageStoreService.java:42) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.packages.PackageStoreClientLibrary.getExecutablePackage(PackageStoreClientLibrary.java:33) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.PackageFactory.getExecutablePackage(PackageFactory.java:29) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.bots.BotStoreClientLibrary.getBot(BotStoreClientLibrary.java:35) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.BotFactory.deployBot(BotFactory.java:89) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.core.rest.internal.RestBotAdministration.lambda$deploy$1(RestBotAdministration.java:68) [coreserver-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.BaseRuntime.lambda$submitCallable$1(BaseRuntime.java:120) [runtime-impl-4.4.jar:?]
eddi_1     | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
eddi_1     | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
eddi_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
eddi_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
eddi_1     | 	at java.lang.Thread.run(Thread.java:834) [?:?]
eddi_1     | Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:221) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:191) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at com.sun.proxy.$Proxy90.readDescriptor(Unknown Source) ~[?:?]
eddi_1     | 	at ai.labs.runtime.service.PackageStoreService.getPackageDocumentDescriptor(PackageStoreService.java:40) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	... 11 more
eddi_1     | 2018-11-27 17:46:13,665 ERROR [etp284149112-39] ? (:) - Error while deploying bot! (botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | javax.ws.rs.InternalServerErrorException: Error while deploying bot! (botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | 	at ai.labs.core.rest.internal.RestBotAdministration.lambda$deploy$1(RestBotAdministration.java:80) ~[coreserver-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.BaseRuntime.lambda$submitCallable$1(BaseRuntime.java:120) [runtime-impl-4.4.jar:?]
eddi_1     | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
eddi_1     | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
eddi_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
eddi_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
eddi_1     | 	at java.lang.Thread.run(Thread.java:834) [?:?]
eddi_1     | Caused by: ai.labs.runtime.service.ServiceException: HTTP 404 Not Found
eddi_1     | 	at ai.labs.runtime.service.PackageStoreService.getPackageDocumentDescriptor(PackageStoreService.java:42) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.packages.PackageStoreClientLibrary.getExecutablePackage(PackageStoreClientLibrary.java:33) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.PackageFactory.getExecutablePackage(PackageFactory.java:29) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.bots.BotStoreClientLibrary.getBot(BotStoreClientLibrary.java:35) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.BotFactory.deployBot(BotFactory.java:89) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.core.rest.internal.RestBotAdministration.lambda$deploy$1(RestBotAdministration.java:68) ~[coreserver-4.4.jar:?]
eddi_1     | 	... 6 more
eddi_1     | Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:221) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:191) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at com.sun.proxy.$Proxy90.readDescriptor(Unknown Source) ~[?:?]
eddi_1     | 	at ai.labs.runtime.service.PackageStoreService.getPackageDocumentDescriptor(PackageStoreService.java:40) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.packages.PackageStoreClientLibrary.getExecutablePackage(PackageStoreClientLibrary.java:33) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.PackageFactory.getExecutablePackage(PackageFactory.java:29) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.bots.BotStoreClientLibrary.getBot(BotStoreClientLibrary.java:35) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.BotFactory.deployBot(BotFactory.java:89) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.core.rest.internal.RestBotAdministration.lambda$deploy$1(RestBotAdministration.java:68) ~[coreserver-4.4.jar:?]
eddi_1     | 	... 6 more
eddi_1     | 2018-11-27 17:52:57,374 INFO  [etp284149112-70] ? (:) - Deploying Bot... (environment=unrestricted, botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | 2018-11-27 17:52:57,437 INFO  [etp284149112-70] ? (:) - Bot deployed with status: ERROR (environment=unrestricted, botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | 2018-11-27 17:52:57,437 ERROR [etp284149112-70] ? (:) - Error while deploying bot! (botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | ai.labs.runtime.service.ServiceException: HTTP 404 Not Found
eddi_1     | 	at ai.labs.runtime.service.PackageStoreService.getPackageDocumentDescriptor(PackageStoreService.java:42) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.packages.PackageStoreClientLibrary.getExecutablePackage(PackageStoreClientLibrary.java:33) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.PackageFactory.getExecutablePackage(PackageFactory.java:29) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.bots.BotStoreClientLibrary.getBot(BotStoreClientLibrary.java:35) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.BotFactory.deployBot(BotFactory.java:89) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.core.rest.internal.RestBotAdministration.lambda$deploy$1(RestBotAdministration.java:68) [coreserver-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.BaseRuntime.lambda$submitCallable$1(BaseRuntime.java:120) [runtime-impl-4.4.jar:?]
eddi_1     | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
eddi_1     | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
eddi_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
eddi_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
eddi_1     | 	at java.lang.Thread.run(Thread.java:834) [?:?]
eddi_1     | Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:221) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:191) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at com.sun.proxy.$Proxy90.readDescriptor(Unknown Source) ~[?:?]
eddi_1     | 	at ai.labs.runtime.service.PackageStoreService.getPackageDocumentDescriptor(PackageStoreService.java:40) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	... 11 more
eddi_1     | 2018-11-27 17:52:57,442 ERROR [etp284149112-70] ? (:) - Error while deploying bot! (botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | javax.ws.rs.InternalServerErrorException: Error while deploying bot! (botId=5bfd8292a7b11b0008aedc2a , version=1)
eddi_1     | 	at ai.labs.core.rest.internal.RestBotAdministration.lambda$deploy$1(RestBotAdministration.java:80) ~[coreserver-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.BaseRuntime.lambda$submitCallable$1(BaseRuntime.java:120) [runtime-impl-4.4.jar:?]
eddi_1     | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
eddi_1     | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
eddi_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
eddi_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
eddi_1     | 	at java.lang.Thread.run(Thread.java:834) [?:?]
eddi_1     | Caused by: ai.labs.runtime.service.ServiceException: HTTP 404 Not Found
eddi_1     | 	at ai.labs.runtime.service.PackageStoreService.getPackageDocumentDescriptor(PackageStoreService.java:42) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.packages.PackageStoreClientLibrary.getExecutablePackage(PackageStoreClientLibrary.java:33) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.PackageFactory.getExecutablePackage(PackageFactory.java:29) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.bots.BotStoreClientLibrary.getBot(BotStoreClientLibrary.java:35) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.BotFactory.deployBot(BotFactory.java:89) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.core.rest.internal.RestBotAdministration.lambda$deploy$1(RestBotAdministration.java:68) ~[coreserver-4.4.jar:?]
eddi_1     | 	... 6 more
eddi_1     | Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:221) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:191) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
eddi_1     | 	at com.sun.proxy.$Proxy90.readDescriptor(Unknown Source) ~[?:?]
eddi_1     | 	at ai.labs.runtime.service.PackageStoreService.getPackageDocumentDescriptor(PackageStoreService.java:40) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.packages.PackageStoreClientLibrary.getExecutablePackage(PackageStoreClientLibrary.java:33) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.PackageFactory.getExecutablePackage(PackageFactory.java:29) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.client.bots.BotStoreClientLibrary.getBot(BotStoreClientLibrary.java:35) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.runtime.internal.BotFactory.deployBot(BotFactory.java:89) ~[runtime-impl-4.4.jar:?]
eddi_1     | 	at ai.labs.core.rest.internal.RestBotAdministration.lambda$deploy$1(RestBotAdministration.java:68) ~[coreserver-4.4.jar:?]
eddi_1     | 	... 6 more

```

**Comment by ginccc** [comment]
Looks like the package is not available.
Able to share the configs you put into EDDI ? Or making an export of your bot? 
(<eddi-url>/backup/export/5bfd8292a7b11b0008aedc2a?botVersion=1)

**Comment by ginccc** [comment]
no, i don't think that there is a problem with the setup. I think it is a problem with the configuration files.
The error complains about not finding a package. May it be that you haven't set the packageid and version correctly in the bot configuration file?
