### ISSUE TITLE
Deployment error when I run ApiServer

### ISSUE THREAD

**Issue by FengXMGeek** [labsai/EDDI#129]
I download EDDI-4.4.0 and followed the “launch with VM options
-DEDDI_ENV=[development/production] -Duser.dir=[LOCAL_PATH_TO_EDDI]\apiserver ai.labs.api.ApiServer”。
It shows :
1) Could not find a suitable constructor in ai.labs.behavior.impl.extensions.Connector. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at ai.labs.behavior.impl.extensions.Connector.class(Connector.java:1)
  at ai.labs.behavior.bootstrap.BehaviorModule.configure(BehaviorModule.java:33)
what`s wrong about my steps?

**Comment by FengXMGeek** [comment]
@ginccc 
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by ginccc** [comment]
I assume you are missing lombok (which generates code such as the constructor in this class and many other parts in the app). If you use IntelliJ as IDE, you can simple add lombok as a plugin. After that it will just work fine as expected. I assume other IDEs will have also support for lombok.

Otherwise, follow instructions here: https://projectlombok.org

Let me know it that solves your problem or if there is anything else not working

**Comment by FengXMGeek** [comment]
@ginccc  can`t run still ~
![image](https://user-images.githubusercontent.com/10595266/54255202-0c92cd80-4592-11e9-88ae-7ee9f839da4d.png)
![image](https://user-images.githubusercontent.com/10595266/54255208-16b4cc00-4592-11e9-9c88-c09133e32395.png)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/G:/mvnRepo/com/google/inject/guice/4.2.2/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Could not find a suitable constructor in ai.labs.behavior.impl.extensions.Connector. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at ai.labs.behavior.impl.extensions.Connector.class(Connector.java:1)
  at ai.labs.behavior.bootstrap.BehaviorModule.configure(BehaviorModule.java:33)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at ai.labs.runtime.DependencyInjector.<init>(DependencyInjector.java:38)
	at ai.labs.runtime.DependencyInjector.init(DependencyInjector.java:25)
	at ai.labs.api.ApiServer.main(ApiServer.java:96)
![image](https://user-images.githubusercontent.com/10595266/54255258-4d8ae200-4592-11e9-9b42-9592cc374527.png)

**Comment by ginccc** [comment]
Did you try running maven ? because the maven build should work without any errors.
So i assume that you don't have lombok properly in place
