### ISSUE TITLE
Log shows infinispan database authorization errors with MongoDB

### ISSUE THREAD

**Issue by allisterb** [labsai/EDDI#158]
I deployed the latest EDDI image on OpenShift and the logs have this recurring entry: 
````2020-03-10 14:57:16 [expiration-thread--p3-t1] WARN  o.i.p.manager.PersistenceManagerImpl - ISPN000026: Caught exception purging data container!
com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on eddi to execute command { find: "infinispan_cachestore_ackAwaitingCommands", filter: { expiryTime: { $lte: new Date(1583852236906), $gt: new Date(-1) } }, sort: { _id: -1 }, limit: 1024, $db: "eddi" }' on server 172.30.193.83:27017
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:735)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725)
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:725)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:89)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:196)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:143)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:121)
	at com.mongodb.client.internal.MappingIterable.forEach(MappingIterable.java:59)
	at com.mongodb.client.internal.MappingIterable.into(MappingIterable.java:69)
	at org.infinispan.persistence.mongodb.cache.MongoDBCacheImpl.removeExpiredData(MongoDBCacheImpl.java:131)
	at org.infinispan.persistence.mongodb.store.MongoDBStore.purge(MongoDBStore.java:109)
	at org.infinispan.persistence.manager.PersistenceManagerImpl.lambda$purgeExpired$6(PersistenceManagerImpl.java:466)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.infinispan.persistence.manager.PersistenceManagerImpl.purgeExpired(PersistenceManagerImpl.java:469)
	at org.infinispan.expiration.impl.ExpirationManagerImpl.processExpiration(ExpirationManagerImpl.java:111)
	at org.infinispan.expiration.impl.ExpirationManagerImpl$ScheduledTask.run(ExpirationManagerImpl.java:245)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)````
````
I believe the cause is in https://github.com/labsai/EDDI/blob/master/apiserver/config/production/infinispan.xml:
````
 uri="mongodb://${mongodb.hosts}:${mongodb.port}/${mongodb.database}?w=0&amp;connectTimeoutMS=2000"
````

which specifies an anonymous connection to MongoDB but will fail if authorization is enabled on the db.

**Comment by ginccc** [comment]
Hi @allisterb,

thank you for reaching out. I think you are probably right. We usually run in scenarios in which the db runs without authentication. That's why we haven't encountered this issue with infinispan yet. 

quickly looking at it, something like this probably solves the problem:
```
uri="mongodb://${mongodb.username}:${mongodb.password}@${mongodb.hosts}:${mongodb.port}/${mongodb.database}?w=0&amp;connectTimeoutMS=2000"
```
However, this does not work on a db without authentication.

We will take a deeper look at it over the next few days!

Thanks for reporting this!

**Comment by ginccc** [comment]
Hi @allisterb,

You were right about your assumptions regarding the anonymous connection. We have refactored the corresponding code and have published a new version alongside some library updates. 

Please check out EDDI version 4.8.2 (already published on openshift catalog as well) and let me know if this resolves your problem. 

Best,
Gregor
