### ISSUE TITLE
How do I start this locally

### ISSUE THREAD

**Issue by jloveric** [labsai/EDDI#57]
I don't know java so how do I run this?  I've installed mongodb and installed the source.  The installation indicates "BUILD SUCCESS".  For launch I see the instructions

"launch with VM options
-DEDDI_ENV=[development/production] -Duser.dir=[LOCAL_PATH_TO_EDDI]\apiserver ai.labs.api.ApiServer"

I'm running locally from within the EDDI base directory, so what is the full command? I've tried

java -classpath '.:lib/*' -DEDDI_ENV=development -Duser.dir=/Users/myname/PROGRAMS/EDDI/apiserver ai.labs.api.ApiServer

but get the error "Error: Could not find or load main class ai.labs.api.ApiServe" assume I need to set the class path somewhere.

Also, will the command ./start_eddi.sh? What should I set EDDI_JAVA_ENV_ to?

I'm running on mac.

Thanks

**Comment by ginccc** [comment]
You have multiple options on how to run eddi:
*) within an IDE such as intellij , just configure it as a maven project and define the -DEDDI_ENV=[development/production] as well as the working directory in the run config and let it fly
*) run the maven build with "maven clean install"; after this you will find a zip file in this location EDDI\apiserver\target\ called "apiserver-4.1-package.zip". unzip it into a folder and run the executables, depending on your OS, in your case the .sh file. 
*) Use "docker-compose" to spin up eddi as well as DB (see https://hub.docker.com/r/labsai/eddi/); I'd recommend THIS ONE, if you don't know java and only wanna use EDDI rather then develop code

hope that helps :) 
let me know if you need further assistance!

Gregor

**Comment by dangokuson** [comment]
Gregor, how can I debug on Netbeans IDE from source code? I'm running on MAC.

Thanks

**Comment by ginccc** [comment]
Hi dgks0n,
personally I am using Intellij for development, so I am not familiar with the concrete steps in netbeans for debugging. 
Nonetheless, it should be fairly simple, just start the ai.labs.api.ApiServer class in debug mode. The you can put your breakpoint in an implementation of any rest interfaces.
ai.labs.rest.rest.IRestBotEngine / ai.labs.core.rest.internal.RestBotEngine for instance would be a good starting point to look at.

**Comment by dgks0n** [comment]
Hi Gregor,
Thanks for sharing. Is this [-Xbootclasspath/p:'.:lib/alpn-boot-8.1.11.v20170118.jar'] VN option is required for running/debugging from source code?

I could not run without that VM option.

**Comment by ginccc** [comment]
oh ... yes, it is required since the latest version that supports http2. Forgot to update the docs about that, sorry for this inconvenience!

**Comment by kumarkrish85** [comment]
Hi @ginccc ,

I am have successfully built the code with maven and started the mongo DB as well. When i use the command to start the server, it always gives an error

`D:\EDDI-master\apiserver\target\apiserver-4.4-package>java -Xbootclasspath/p:'.:lib/alpn-boot-8.1.12.v20180117.jar' -DEDDI_ENV=development -Duser.dir=D:\EDDI-master\apiserver\ ai.labs.api.ApiServer
Error: Could not find or load main class ai.labs.api.ApiServer`

Please suggest

**Comment by ginccc** [comment]
Hi @kumarkrish85,

I suspect "-Duser.dir=D:\EDDI-master\apiserver\" is the issue here, as this only will work when you start it from within your IDE.
Also, you are missing the include for the entire lib dir: -classpath '.:lib/*'

Let me know if that worked for you..

**Comment by kumarkrish85** [comment]
Hi @ginccc 

Thanks for your suggestion. I have started the server using this below command

`java -Xbootclasspath/p:"lib/alpn-boot-8.1.12.v20180117.jar" -cp ".;lib/*" -DEDDI_ENV=development ai.labs.api.ApiServer `

Regards,
Krishna

**Comment by jtymel** [comment]
Hi @ginccc 

I've just run into similar problem - I'm not able to start EDDI locally either.
Every time I get furthest I can I'll get the same error:
``Error: Could not find or load main class ai.labs.api.ApiServer``

I get this error no matter whether using 
``sudo docker-compose -f docker-compose.yml -f docker-compose.local.yml up``
from the already built (via ``mvn clean install``) root directory;
or within extracted ``apiserver-4.4-package`` folder (as you pointed earlier) running
``java -Xbootclasspath/p:'.:lib/alpn-boot-8.1.11.v20170118.jar' -cp ".;lib/*" -DEDDI_ENV=development ai.labs.api.ApiServer``

My OS is Ubuntu 16.04 LTS and I use java version openjdk version "1.8.0_171".

Could you please point me out what am I missing or doing wrong? Thank you very much in advance :)

PS: If I run docker command propagated at [Getting started page](https://labsai.atlassian.net/wiki/spaces/EDDI/pages/167823/Getting+started) I get a strange mongo exception (no matter whether MongoDB is running or not). Not sure if this point helps or not though.

> $ sudo docker run -it -e "EDDI_ENV=development" labsai/eddi
dynamically set java arguments: 
memory params: 
2018-07-31 10:56:30,880 INFO  [main] ? (:) - eddi v4.4.0
2018-07-31 10:56:31,104 INFO  [main] ? (:) - Cluster created with settings {hosts=[localhost:27017], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2018-07-31 10:56:31,104 INFO  [main] ? (:) - Adding discovered server localhost:27017 to client view of cluster
2018-07-31 10:56:31,139 INFO  [cluster-ClusterId{value='5b60405f46e0fb000c0e60a4', description='null'}-localhost:27017] ? (:) - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.6.1.jar:?]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.6.1.jar:?]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:114) [mongodb-driver-core-3.6.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_151]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_151]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_151]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:59) ~[mongodb-driver-core-3.6.1.jar:?]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:57) ~[mongodb-driver-core-3.6.1.jar:?]
	... 3 more
2018-07-31 10:56:31,422 INFO  [ServerRuntime] ? (:) - Logging initialized @1960ms to org.eclipse.jetty.util.log.Slf4jLog
2018-07-31 10:56:31,526 INFO  [ServerRuntime] ? (:) - CrossSiteScriptFilter has been enabled...
2018-07-31 10:56:31,529 INFO  [ServerRuntime] ? (:) - jetty-9.4.7.v20170914
2018-07-31 10:56:31,568 INFO  [ServerRuntime] ? (:) - DefaultSessionIdManager workerName=node0
2018-07-31 10:56:31,569 INFO  [ServerRuntime] ? (:) - No SessionScavenger set, using defaults
2018-07-31 10:56:31,570 INFO  [ServerRuntime] ? (:) - Scavenging every 600000ms
2018-07-31 10:56:31,592 INFO  [ServerRuntime] ? (:) - RESTEASY002225: Deploying javax.ws.rs.core.Application: class ai.labs.api.ApplicationConfiguration
2018-07-31 10:56:31,594 INFO  [ServerRuntime] ? (:) - RESTEASY002205: Adding provider class ai.labs.staticresources.impl.interceptor.ContentTypeInterceptor from Application class ai.labs.api.ApplicationConfiguration
2018-07-31 10:56:31,594 INFO  [ServerRuntime] ? (:) - RESTEASY002205: Adding provider class ai.labs.permission.interceptor.PermissionRequestInterceptor from Application class ai.labs.api.ApplicationConfiguration
2018-07-31 10:56:31,595 INFO  [ServerRuntime] ? (:) - RESTEASY002205: Adding provider class ai.labs.permission.interceptor.PermissionResponseInterceptor from Application class ai.labs.api.ApplicationConfiguration
2018-07-31 10:56:31,595 INFO  [ServerRuntime] ? (:) - RESTEASY002205: Adding provider class ai.labs.resources.impl.interceptors.DocumentDescriptorInterceptor from Application class ai.labs.api.ApplicationConfiguration
2018-07-31 10:56:31,595 INFO  [ServerRuntime] ? (:) - RESTEASY002205: Adding provider class ai.labs.server.exception.IllegalArgumentExceptionMapper from Application class ai.labs.api.ApplicationConfiguration
2018-07-31 10:56:31,595 INFO  [ServerRuntime] ? (:) - RESTEASY002205: Adding provider class ai.labs.server.JacksonConfig from Application class ai.labs.api.ApplicationConfiguration
2018-07-31 10:56:31,595 INFO  [ServerRuntime] ? (:) - RESTEASY002205: Adding provider class ai.labs.server.providers.URIMessageBodyProvider from Application class ai.labs.api.ApplicationConfiguration
2018-07-31 10:56:31,606 INFO  [ServerRuntime] ? (:) - RESTEASY011025: registering provider instance for io.swagger.jaxrs.listing.SwaggerSerializers
2018-07-31 10:56:31,607 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.permission.rest.IRestPermissionStore
2018-07-31 10:56:31,647 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.documentdescriptor.IRestDocumentDescriptorStore
2018-07-31 10:56:31,657 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.extensions.IRestExtensionStore
2018-07-31 10:56:31,658 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.expression.IRestExpression
2018-07-31 10:56:31,659 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.deployment.IRestDeploymentStore
2018-07-31 10:56:31,660 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.bots.IRestBotStore
2018-07-31 10:56:31,668 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.packages.IRestPackageStore
2018-07-31 10:56:31,674 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.parser.IRestParserStore
2018-07-31 10:56:31,682 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.regulardictionary.IRestRegularDictionaryStore
2018-07-31 10:56:31,689 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.behavior.IRestBehaviorStore
2018-07-31 10:56:31,695 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.output.IRestOutputStore
2018-07-31 10:56:31,701 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.memory.rest.IRestConversationStore
2018-07-31 10:56:31,705 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.http.IRestHttpCallsStore
2018-07-31 10:56:31,709 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.resources.rest.output.keys.IRestOutputKeys
2018-07-31 10:56:31,710 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.group.rest.IRestGroupStore
2018-07-31 10:56:31,712 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.user.rest.IRestUserStore
2018-07-31 10:56:31,714 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.parser.rest.IRestSemanticParser
2018-07-31 10:56:31,718 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.testing.rest.IRestTestCaseStore
2018-07-31 10:56:31,721 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.testing.rest.IRestTestCaseRuntime
2018-07-31 10:56:31,722 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.staticresources.rest.IRestHtmlApiResource
2018-07-31 10:56:31,722 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.staticresources.rest.IRestHtmlChatResource
2018-07-31 10:56:31,723 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.staticresources.rest.IRestBinaryResource
2018-07-31 10:56:31,727 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.rest.rest.IRestBotEngine
2018-07-31 10:56:31,735 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.rest.rest.IRestBotAdministration
2018-07-31 10:56:31,737 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.rest.rest.IRestHealthCheck
2018-07-31 10:56:31,738 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.facebookmessenger.IFacebookEndpoint
2018-07-31 10:56:31,741 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.backupservice.IRestExportService
2018-07-31 10:56:31,742 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for ai.labs.backupservice.IRestImportService
2018-07-31 10:56:31,743 INFO  [ServerRuntime] ? (:) - RESTEASY011020: registering factory for io.swagger.jaxrs.listing.ApiListingResource
2018-07-31 10:56:31,859 INFO  [ServerRuntime] ? (:) - Reflections took 82 ms to scan 15 urls, producing 339 keys and 515 values 
2018-07-31 10:56:32,022 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,022 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,022 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,083 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,083 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,083 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,088 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,088 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,088 WARN  [ServerRuntime] ? (:) - Unknown implicit parameter type: []
2018-07-31 10:56:32,225 INFO  [ServerRuntime] ? (:) - wro4j version: 1.8.0
2018-07-31 10:56:32,225 INFO  [ServerRuntime] ? (:) - wro4j configuration: ro.isdc.wro.config.jmx.WroConfiguration@4354b2ac[
  cacheUpdatePeriod=100
  modelUpdatePeriod=0
  resourceWatcherUpdatePeriod=0
  resourceWatcherAsync=true
  gzipEnabled=true
  debug=true
  ignoreMissingResources=true
  cacheGzippedContent=true
  jmxEnabled=true
  wroManagerClassName=ro.isdc.wro.manager.factory.ConfigurableWroManagerFactory
  encoding=UTF-8
  mbeanName=
  header=
  connectionTimeout=2000
  parallelPreprocessing=false
  ignoreEmptyGroup=true
  ignoreFailingProcessor=false
  minimizeEnabled=false
]
2018-07-31 10:56:32,269 INFO  [ServerRuntime] ? (:) - Started o.e.j.s.ServletContextHandler@3b996755{/,file:///apiserver/resources/,AVAILABLE}
2018-07-31 10:56:32,282 INFO  [ServerRuntime] ? (:) - x509=X509@66f212f2(eddi,h=[],w=[]) for SslContextFactory@333a79c4(file:///apiserver/resources/keystore/eddi_selfsigned.jks,null)
2018-07-31 10:56:32,315 INFO  [ServerRuntime] ? (:) - Started ServerConnector@771e81be{SSL,[ssl, alpn, h2, http/1.1]}{0.0.0.0:7443}
2018-07-31 10:56:32,316 INFO  [ServerRuntime] ? (:) - Started ServerConnector@5ae2e8e9{HTTP/1.1,[http/1.1]}{0.0.0.0:7070}
2018-07-31 10:56:32,316 INFO  [ServerRuntime] ? (:) - Started @2856ms
2018-07-31 10:56:32,402 INFO  [ServerRuntime] ? (:) - Starting auto deployment of bots...
2018-07-31 10:56:32,410 INFO  [ServerRuntime] ? (:) - Cluster description not yet available. Waiting for 30000 ms before timing out
>

**Comment by ginccc** [comment]
pls use docker container v4.3 or release branch 4.3

4.4 is instable a the moment as it is in current development
